encoding: utf-8
title: Dong-sik Choi
description: Data Science study

url: http://dongsikchoi.github.io
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
  - title: Home
    url: /index.html
  - title: About
    url: /about
  - title: Contact
    url: /contact

social:
  github: dongsikchoi
  email: dongsikchoi.dev@gmail.com

timezone: Asia/Seoul
